name: TweetsSync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'
jobs:
  TweetSync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile

      - name: Sync Tweets
        run: pnpm run sync-tweet
        env:
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          SUPABASE_ANON: ${{ secrets.SUPABASE_ANON }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
